# #######################################
# Recipe for performing enhancement in the time domain
# To change model, switch "!include:" statement
# To change loss function, change
# #######################################


# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 3234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

data_folder: /localscratch/noisy-vctk-16k
test_clean_folder: !ref <data_folder>/clean_testset_wav_16k/

output_folder: !ref ./results/waveform_map/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
enhanced_folder: !ref <output_folder>/enhanced

# Basic parameters
use_tensorboard: True
tensorboard_logs: !ref <output_folder>/logs/

# FFT parameters
Sample_rate: 16000
Win_length: 32
Hop_length: 16
N_fft: 512
window_fn: !name:torch.hamming_window

# Data files
train_annotation: !ref <output_folder>/train.json
valid_annotation: !ref <output_folder>/valid.json
test_annotation: !ref <output_folder>/test.json
skip_prep: False

# Training Parameters
number_of_epochs: 150
N_batch: 1
lr: 0.001
device: 'cuda:0'
sorting: ascending
dataloader_options:
    batch_size: !ref <N_batch>

# Change this include statement to use different model
models: !include:models/FCN.yaml

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

modules:
    model: !ref <models[model]>

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <models[model]>
        counter: !ref <epoch_counter>

# Change this cost function to use different loss
compute_cost: !name:speechbrain.nnet.losses.mse_loss
# compute_cost: !name:speechbrain.nnet.loss.stoi_loss.stoi_loss

compute_STFT: !new:speechbrain.processing.features.STFT
    sample_rate: !ref <Sample_rate>
    win_length: !ref <Win_length>
    hop_length: !ref <Hop_length>
    n_fft: !ref <N_fft>
    window_fn: !ref <window_fn>

compute_ISTFT: !new:speechbrain.processing.features.ISTFT
    sample_rate: !ref <Sample_rate>
    win_length: !ref <Win_length>
    hop_length: !ref <Hop_length>
    window_fn: !ref <window_fn>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

# Tensorboard logger (optional)
tensorboard_train_logger: !new:speechbrain.utils.train_logger.TensorboardLogger
    save_dir: !ref <tensorboard_logs>
