# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/teachers_save/<seed>

# Data files
data_folder: !PLACEHOLDER  # e.g. /path/to/TIMIT
train_annotation: !ref <output_folder>/train.json
valid_annotation: !ref <output_folder>/dev.json
test_annotation: !ref <output_folder>/test.json

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>

valid_dataloader_opts:
    batch_size: !ref <batch_size>

test_dataloader_opts:
    batch_size: !ref <batch_size>

# Training parameters
number_of_epochs: 1
batch_size: 8
sorting: ascending

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40

# Model parameters
emb_size: 128

# Outputs
output_neurons: 40
blank_index: !ref <output_neurons> - 1
bos_index: !ref <output_neurons> - 1
eos_index: !ref <output_neurons> - 1

# Decoding parameters
min_decode_ratio: 0.0
max_decode_ratio: 1.0
beam_size: 16
eos_threshold: 1.5

# teacher models
num_tea: 10

# .txt file containing paths for saved teacher models.
# e.g. each line is /path/to/model.ckpt
tea_models_dir: !PLACEHOLDER

# distillation parameters
# Temperature
temperature: 1
# distillation weight alpha
alpha: 1
# different stages in dataset
stage: ["train", "valid", "test"]

# tea0
tea0_enc: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !name:torch.nn.LeakyReLU
    dropout: 0.15
    cnn_blocks: 2
    cnn_channels: (128, 256)
    cnn_kernelsize: (3, 3)
    time_pooling: True
    rnn_layers: 4
    rnn_neurons: 512
    rnn_bidirectional: True
    dnn_blocks: 2
    dnn_neurons: 512

tea0_emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

tea0_dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: 512
    input_size: !ref <emb_size>
    rnn_type: gru
    attn_type: location
    hidden_size: 256
    attn_dim: 256
    num_layers: 1
    scaling: 1.0
    channels: 10
    kernel_size: 100
    re_init: True
    dropout: 0.5

tea0_ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 512
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 blank

tea0_seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 256
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 eos

# tea1
tea1_enc: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !name:torch.nn.LeakyReLU
    dropout: 0.3
    cnn_blocks: 2
    cnn_channels: (128, 256)
    cnn_kernelsize: (3, 3)
    time_pooling: True
    rnn_layers: 4
    rnn_neurons: 512
    rnn_bidirectional: True
    dnn_blocks: 2
    dnn_neurons: 512

tea1_emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

tea1_dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: 512
    input_size: !ref <emb_size>
    rnn_type: gru
    attn_type: location
    hidden_size: 256
    attn_dim: 256
    num_layers: 1
    scaling: 1.0
    channels: 10
    kernel_size: 100
    re_init: True
    dropout: 0.5

tea1_ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 512
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 blank

tea1_seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 256
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 eos

# tea2
tea2_enc: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !name:torch.nn.LeakyReLU
    dropout: 0.3
    cnn_blocks: 2
    cnn_channels: (128, 256)
    cnn_kernelsize: (3, 3)
    time_pooling: True
    rnn_layers: 4
    rnn_neurons: 512
    rnn_bidirectional: True
    dnn_blocks: 2
    dnn_neurons: 512

tea2_emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

tea2_dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: 512
    input_size: !ref <emb_size>
    rnn_type: gru
    attn_type: location
    hidden_size: 256
    attn_dim: 256
    num_layers: 1
    scaling: 1.0
    channels: 10
    kernel_size: 100
    re_init: True
    dropout: 0.5

tea2_ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 512
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 blank

tea2_seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 256
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 eos

# tea3
tea3_enc: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !name:torch.nn.LeakyReLU
    dropout: 0.2
    cnn_blocks: 2
    cnn_channels: (128, 256)
    cnn_kernelsize: (3, 3)
    time_pooling: True
    rnn_layers: 5
    rnn_neurons: 512
    rnn_bidirectional: True
    dnn_blocks: 2
    dnn_neurons: 512

tea3_emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

tea3_dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: 512
    input_size: !ref <emb_size>
    rnn_type: lstm
    attn_type: location
    hidden_size: 256
    attn_dim: 256
    num_layers: 1
    scaling: 1.0
    channels: 10
    kernel_size: 100
    re_init: True
    dropout: 0.5

tea3_ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 512
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 blank

tea3_seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 256
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 eos

# tea4
tea4_enc: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !name:torch.nn.LeakyReLU
    dropout: 0.3
    cnn_blocks: 2
    cnn_channels: (128, 256)
    cnn_kernelsize: (3, 3)
    time_pooling: True
    rnn_layers: 4
    rnn_neurons: 512
    rnn_bidirectional: True
    dnn_blocks: 2
    dnn_neurons: 512

tea4_emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

tea4_dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: 512
    input_size: !ref <emb_size>
    rnn_type: gru
    attn_type: location
    hidden_size: 256
    attn_dim: 256
    num_layers: 1
    scaling: 1.0
    channels: 10
    kernel_size: 100
    re_init: True
    dropout: 0.5

tea4_ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 512
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 blank

tea4_seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 256
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 eos

# tea5
tea5_enc: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !name:torch.nn.LeakyReLU
    dropout: 0.3
    cnn_blocks: 2
    cnn_channels: (128, 256)
    cnn_kernelsize: (3, 3)
    time_pooling: True
    rnn_layers: 4
    rnn_neurons: 320
    rnn_bidirectional: True
    dnn_blocks: 2
    dnn_neurons: 320

tea5_emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

tea5_dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: 320
    input_size: !ref <emb_size>
    rnn_type: lstm
    attn_type: location
    hidden_size: 256
    attn_dim: 256
    num_layers: 1
    scaling: 1.0
    channels: 10
    kernel_size: 100
    re_init: True
    dropout: 0.5

tea5_ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 320
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 blank

tea5_seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 256
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 eos

# tea6
tea6_enc: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !name:torch.nn.LeakyReLU
    dropout: 0.3
    cnn_blocks: 1
    cnn_channels: (128, 256)
    cnn_kernelsize: (3, 3)
    time_pooling: True
    rnn_layers: 4
    rnn_neurons: 320
    rnn_bidirectional: True
    dnn_blocks: 2
    dnn_neurons: 320

tea6_emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

tea6_dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: 320
    input_size: !ref <emb_size>
    rnn_type: lstm
    attn_type: location
    hidden_size: 256
    attn_dim: 256
    num_layers: 1
    scaling: 1.0
    channels: 10
    kernel_size: 100
    re_init: True
    dropout: 0.5

tea6_ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 320
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 blank

tea6_seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 256
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 eos

# tea7
tea7_enc: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !name:torch.nn.LeakyReLU
    dropout: 0.15
    cnn_blocks: 2
    cnn_channels: (128, 256)
    cnn_kernelsize: (3, 3)
    time_pooling: True
    rnn_layers: 4
    rnn_neurons: 640
    rnn_bidirectional: True
    dnn_blocks: 2
    dnn_neurons: 512

tea7_emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

tea7_dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: 512
    input_size: !ref <emb_size>
    rnn_type: gru
    attn_type: location
    hidden_size: 256
    attn_dim: 256
    num_layers: 1
    scaling: 1.0
    channels: 10
    kernel_size: 100
    re_init: True
    dropout: 0.5

tea7_ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 512
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 blank

tea7_seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 256
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 eos

# tea8
tea8_enc: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !name:torch.nn.LeakyReLU
    dropout: 0.3
    cnn_blocks: 2
    cnn_channels: (128, 256)
    cnn_kernelsize: (3, 3)
    time_pooling: True
    rnn_layers: 5
    rnn_neurons: 512
    rnn_bidirectional: True
    dnn_blocks: 2
    dnn_neurons: 512

tea8_emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

tea8_dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: 512
    input_size: !ref <emb_size>
    rnn_type: lstm
    attn_type: location
    hidden_size: 256
    attn_dim: 256
    num_layers: 1
    scaling: 1.0
    channels: 10
    kernel_size: 100
    re_init: True
    dropout: 0.5

tea8_ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 512
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 blank

tea8_seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 256
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 eos

# tea9
tea9_enc: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !name:torch.nn.LeakyReLU
    dropout: 0.15
    cnn_blocks: 2
    cnn_channels: (128, 256)
    cnn_kernelsize: (3, 3)
    time_pooling: True
    rnn_layers: 4
    rnn_neurons: 512
    rnn_bidirectional: True
    dnn_blocks: 2
    dnn_neurons: 512

tea9_emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

tea9_dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: 512
    input_size: !ref <emb_size>
    rnn_type: gru
    attn_type: location
    hidden_size: 256
    attn_dim: 256
    num_layers: 1
    scaling: 1.0
    channels: 10
    kernel_size: 100
    re_init: True
    dropout: 0.5

tea9_ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 512
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 blank

tea9_seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: 256
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 eos


log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

normalize: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

compute_features: !new:speechbrain.lobes.features.Fbank
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    n_mels: !ref <n_mels>
