# ################################
# Pretrain perceptual model for mimic loss
# Authors: Peter Plantinga 2020, 2021
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1256
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/perceptual_model/<seed>
stats_file: !ref <output_folder>/stats.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: !PLACEHOLDER  # e.g. /path/to/Voicebank
train_annotation: !ref <data_folder>/train.json
valid_annotation: !ref <data_folder>/valid.json
test_annotation: !ref <data_folder>/test.json
skip_prep: False

# Training parameters
number_of_epochs: 20
ctc_epochs: 5
batch_size: 8
lr: 0.0005
sorting: ascending
target_type: phones
checkpoint_avg: 1
eval_min_key: phonesER
eval_max_key: null
train_loader_options:
    batch_size: !ref <batch_size>
valid_loader_options:
    batch_size: !ref <batch_size>
    shuffle: False
test_loader_options:
    batch_size: !ref <batch_size>
    shuffle: False

# Loss weights
enhance_type: null  # null, mapping, masking
enhance_weight: 0.0
mimic_weight: 0.0
ctc_weight: 1.0
ctc_type: clean  # null, clean, joint
seq_weight: 1.0
seq_type: clean  # null, clean, joint
label_smoothing: 0.1

# Set this to the path of a pretrained model to load before training
pretrained_path: {}
frozen_models: []

# Feature parameters
sample_rate: 16000
n_fft: 512
win_length: 32
hop_length: 16

# Outputs
output_neurons: 42
blank_index: !ref <output_neurons> - 1
bos_index: !ref <output_neurons> - 1
eos_index: !ref <output_neurons> - 1

# Import perceptual model hyperparams
model: !include:models/perceptual_model.yaml
    output_neurons: !ref <output_neurons>
    n_fft: !ref <n_fft>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

compute_stft: !new:speechbrain.processing.features.STFT
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    win_length: !ref <win_length>
    hop_length: !ref <hop_length>

compute_istft: !new:speechbrain.processing.features.ISTFT
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    win_length: !ref <win_length>
    hop_length: !ref <hop_length>

spectral_magnitude: !name:speechbrain.processing.features.spectral_magnitude
    power: 0.5

beam_searcher: !new:speechbrain.decoders.seq2seq.S2SRNNBeamSearcher
    embedding: !ref <model[tgt_embedding]>
    decoder: !ref <model[recognizer]>
    linear: !ref <model[seq_output]>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: 0
    max_decode_ratio: 1
    beam_size: 16

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

lr_annealing: !new:speechbrain.nnet.schedulers.StepScheduler
    initial_value: !ref <lr>
    decay_factor: 0.5
    decay_drop: 3

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

modules:
    src_embedding: !ref <model[src_embedding]>
    tgt_embedding: !ref <model[tgt_embedding]>
    recognizer: !ref <model[recognizer]>
    ctc_output: !ref <model[ctc_output]>
    seq_output: !ref <model[seq_output]>

jit_module_keys: [src_embedding]

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        src_embedding: !ref <model[src_embedding]>
        tgt_embedding: !ref <model[tgt_embedding]>
        recognizer: !ref <model[recognizer]>
        ctc_output: !ref <model[ctc_output]>
        seq_output: !ref <model[seq_output]>
        counter: !ref <epoch_counter>

ctc_loss: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>
seq_loss: !name:speechbrain.nnet.losses.nll_loss
    label_smoothing: !ref <label_smoothing>
err_rate_stats: !name:speechbrain.utils.metric_stats.ErrorRateStats

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
