# ################################
# Model: VGG2 + LiGRU with time pooling for efficiency
# Additions: TimeDomainSpecAugment
# Authors: Mirco Ravanelli & Peter Plantinga 2020
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1428
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/robust_asr/<seed>
stats_file: !ref <output_folder>/stats.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: !PLACEHOLDER  # e.g. /path/to/Voicebank
data_folder_rirs: !ref <data_folder>
train_annotation: !ref <data_folder>/train.json
valid_annotation: !ref <data_folder>/valid.json
test_annotation: !ref <data_folder>/test.json
skip_prep: False

# Training parameters
number_of_epochs: 30
ctc_epochs: 0
batch_size: 8
lr: 0.0001
token_type: unigram
target_type: words
checkpoint_avg: 5  # average this many checkpoints for eval
sorting: ascending
character_coverage: 1.0
eval_max_key: null
eval_min_key: null
train_loader_options:
    batch_size: !ref <batch_size>
valid_loader_options:
    batch_size: !ref <batch_size>
    shuffle: False
test_loader_options:
    batch_size: !ref <batch_size>
    shuffle: False
epochs_before_lr_drop: 3

# Loss weights
enhance_type: masking  # null, mapping, masking, noisy, clean
enhance_weight: 0.0
mimic_weight: 0.0
ctc_weight: 1.0
ctc_type: joint  # null, clean, joint
seq_weight: 1.0
seq_type: joint  # null, clean, joint
alignment_weight: 0.0
label_smoothing: 0.1
mask_weight: 0.7

# Here, the pretrained models are downloaded from the speechbrain
# HuggingFace repository. However, a local path pointing to a directory with
# your checkpoints may also be specified instead (see pretrainer below)
pretrained_asr_path: speechbrain/asr-crdnn-rnnlm-librispeech
pretrained_enhance_path: speechbrain/mtl-mimic-voicebank

frozen_models: [enhance_model, lm_model, src_embedding]
unfreeze_epoch: !ref <epochs_before_lr_drop> + 1
unfrozen_models: [src_embedding]

# Feature parameters
sample_rate: 16000
n_fft: 512
win_length: 32
hop_length: 16
n_mels: 40

# Outputs
output_neurons: 1000
blank_index: 0
bos_index: 0
eos_index: 0
unk_index: 0

# Decoding params
min_decode_ratio: 0.0
max_decode_ratio: 1.0
beam_size: 32
eos_threshold: 10.0
using_max_attn_shift: True
max_attn_shift: 240
lm_weight: 0.15
coverage_penalty: 1.5
temperature: 1.25
temperature_lm: 1.25

enhance_model: !include:models/enhance_model.yaml
    n_fft: !ref <n_fft>

enhance_pretrained: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        enhance_model: !ref <enhance_model[enhance_model]>
    paths:
        enhance_model: !ref <pretrained_enhance_path>/enhance_model.ckpt

normalizer: !new:speechbrain.processing.features.InputNormalization
tokenizer: !new:sentencepiece.SentencePieceProcessor

asr_model: !include:models/asr_model.yaml
    n_mels: !ref <n_mels>
    dropout_rate: 0.1
    output_neurons: !ref <output_neurons>

model: !new:torch.nn.ModuleList
    - - !ref <asr_model[src_embedding]>
      - !ref <asr_model[tgt_embedding]>
      - !ref <asr_model[recognizer]>
      - !ref <asr_model[ctc_output]>
      - !ref <asr_model[seq_output]>

# Change the path to use a local model instead of the remote one
asr_pretrained: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        normalizer: !ref <normalizer>
        tokenizer: !ref <tokenizer>
        asr_model: !ref <model>
        lm: !ref <asr_model[lm_model]>
    paths:
        normalizer: !ref <pretrained_asr_path>/normalizer.ckpt
        tokenizer: !ref <pretrained_asr_path>/tokenizer.ckpt
        asr_model: !ref <pretrained_asr_path>/asr.ckpt
        lm: !ref <pretrained_asr_path>/lm.ckpt

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

compute_stft: !new:speechbrain.processing.features.STFT
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    win_length: !ref <win_length>
    hop_length: !ref <hop_length>

compute_istft: !new:speechbrain.processing.features.ISTFT
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    win_length: !ref <win_length>
    hop_length: !ref <hop_length>

spectral_magnitude: !name:speechbrain.processing.features.spectral_magnitude
    power: 0.5

resynth: !name:speechbrain.processing.signal_processing.resynthesize
    stft: !ref <compute_stft>
    istft: !ref <compute_istft>

env_corr: !new:speechbrain.lobes.augment.EnvCorrupt
    openrir_folder: !ref <data_folder_rirs>
    babble_prob: 0.0
    reverb_prob: 0.0
    noise_prob: 1.0
    noise_snr_low: 0
    noise_snr_high: 15

augment: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
fbank: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>
    sample_rate: !ref <sample_rate>

beam_searcher: !new:speechbrain.decoders.seq2seq.S2SRNNBeamSearchLM
    embedding: !ref <asr_model[tgt_embedding]>
    decoder: !ref <asr_model[recognizer]>
    linear: !ref <asr_model[seq_output]>
    language_model: !ref <asr_model[lm_model]>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <beam_size>
    eos_threshold: !ref <eos_threshold>
    using_max_attn_shift: !ref <using_max_attn_shift>
    max_attn_shift: !ref <max_attn_shift>
    coverage_penalty: !ref <coverage_penalty>
    lm_weight: !ref <lm_weight>
    temperature: !ref <temperature>
    temperature_lm: !ref <temperature_lm>

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

opt_class: !name:torch.optim.AdamW
    lr: !ref <lr>
    weight_decay: 0.00005

lr_annealing: !new:speechbrain.nnet.schedulers.StepScheduler
    initial_value: !ref <lr>
    decay_factor: 0.7
    decay_drop: !ref <epochs_before_lr_drop>

modules:
    enhance_model: !ref <enhance_model[enhance_model]>
    src_embedding: !ref <asr_model[src_embedding]>
    tgt_embedding: !ref <asr_model[tgt_embedding]>
    recognizer: !ref <asr_model[recognizer]>
    ctc_output: !ref <asr_model[ctc_output]>
    seq_output: !ref <asr_model[seq_output]>
    lm_model: !ref <asr_model[lm_model]>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        enhance_model: !ref <enhance_model[enhance_model]>
        src_embedding: !ref <asr_model[src_embedding]>
        tgt_embedding: !ref <asr_model[tgt_embedding]>
        recognizer: !ref <asr_model[recognizer]>
        ctc_output: !ref <asr_model[ctc_output]>
        seq_output: !ref <asr_model[seq_output]>
        counter: !ref <epoch_counter>
        normalizer: !ref <normalizer>

pretrain_checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: pretrain
    recoverables:
        model: !ref <model>
        normalizer: !ref <normalizer>

enhance_loss: !name:speechbrain.nnet.losses.mse_loss
mimic_loss: !name:speechbrain.nnet.losses.mse_loss
ctc_loss: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>
seq_loss: !name:speechbrain.nnet.losses.nll_loss
    label_smoothing: !ref <label_smoothing>

enhance_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.mse_loss
        reduction: batch
mimic_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.mse_loss
        reduction: batch
estoi_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:train.estoi_eval
    n_jobs: 30
pesq_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:train.pesq_eval
    n_jobs: 30
err_rate_stats: !name:speechbrain.utils.metric_stats.ErrorRateStats
    merge_tokens: True
    space_token: " "

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
