# minibatch related
batch-size: 30
maxlen-in: 800
maxlen-out: 150

# optimization related
criterion: loss
early-stop-criterion: "validation/main/loss"
sortagrad: 0
opt: adadelta
epochs: 15
patience: 3

# network architecture
## encoder related
etype: blstmp
elayers: 4
eunits: 320
eprojs: 320
subsample: "1_2_2_1_1"
dropout-rate: 0.0
## decoder related
dtype: lstm
dlayers: 1
dec-embed-dim: 300
dunits: 300
dropout-rate-decoder: 0.1
dropout-rate-embed-decoder: 0.1
## joint network related
joint-dim: 300

# transducer related
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"
